### ISSUE TITLE
Another general question: I'm looking to have each mobs stats generated based on level/maybe random traits.

### ISSUE THREAD

**Issue by ratacat** [azigler/pinwheel#2]
In Ranvier, it currently seems like I'd have to get in and modify Room.js or Npc.js (which Nephila and Shawn seem to think is a bad idea) , as the YAML file doesn't support any level of programming obviously. Is this something you've thought about in any form?

**Comment by azigler** [comment]
I agree with them that this type of job wouldn't be accomplished in the source files. My suggestion for this approach is to abstract the mob generation process and create a "spawner" item for each room. The item can be invisible/immovable, but would keep its state between boots.

I would put a script on this spawner item that

1. checks if it can create a new mob (maybe set a hard cap)
2. tries to instantiate a new mob if there's room
3. modifies the new mob's stats based on internal factors

So instead of assigning mobs to a room in the NPC entry in YAML, you would put the spawner item in the YAML and let it handle the unique mob stats/listeners/anything for that room.

In this approach, you need a custom spawner item for each type of modified NPC. Or you can create a generic one and then configure each spawner once they're loaded. The spawner would then retain its special parameters across reboots, since it would persist. Alternatively, you can write an empty spawner and then define the spawner properties on each room. The spawner could scan the room's metadata for its configuration, then set itself up based on that.

Those are some approaches that immediately come to mind in the current framework!

**Comment by seanohue** [comment]
This can also be done in vanilla Ranvier (as well as Pinwheel) by modifying the NPC in the 'spawn' event. The risk with this, is that other 'spawn' events may rely on the mob's stats. This can be avoided by having the attribute-modifying events emit a 'postspawn' event on the NPC. Then, any behaviors involving the modified attributes should use 'postspawn'.

**Comment by ratacat** [comment]
Thanks @azigler & @seanohue!!  I'm trying some things out, super appreciate it!
